

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Realstate_agentsEntities : DbContext
{
    public Realstate_agentsEntities()
        : base("name=Realstate_agentsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Sys_Company> Sys_Company { get; set; }

    public virtual DbSet<Sys_Users> Sys_Users { get; set; }

    public virtual DbSet<Sys_Notifications> Sys_Notifications { get; set; }

    public virtual DbSet<Tb_Resources> Tb_Resources { get; set; }

    public virtual DbSet<Tb_Videos> Tb_Videos { get; set; }

    public virtual DbSet<Tb_Webinars> Tb_Webinars { get; set; }

    public virtual DbSet<Tb_Docpackages> Tb_Docpackages { get; set; }

    public virtual DbSet<Tb_Docpackages_details> Tb_Docpackages_details { get; set; }

    public virtual DbSet<Tb_Customers> Tb_Customers { get; set; }

    public virtual DbSet<Tb_Process> Tb_Process { get; set; }

    public virtual DbSet<Tb_Quotes> Tb_Quotes { get; set; }

    public virtual DbSet<Tb_Notes> Tb_Notes { get; set; }

    public virtual DbSet<Tb_Posts> Tb_Posts { get; set; }

    public virtual DbSet<Tb_Marketing> Tb_Marketing { get; set; }

    public virtual DbSet<Tb_Network> Tb_Network { get; set; }

    public virtual DbSet<Tb_Options> Tb_Options { get; set; }

}

}

